version: v1
label: rating
components:
  - component_path: components/deviation.yaml
  - component_path: components/variance.yaml
  - component_path: components/autocorrelation.yaml
  - component_path: components/dexliquidity.yaml
  - component_path: components/activeaddress.yaml
  - component_path: components/txvolume.yaml
  - component_path: components/rating_indexer.yaml
